---
name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: What version of Python are you using?
      placeholder: e.g. 3.11.5
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g. Ubuntu 24.04, macOS Sonoma
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      description: Please copy and paste any relevant error output
      render: shell
